default_environment: default
environments:
    default:
        connections:
            duckdb:
                - name: duckdb-default
                  path: duckdb.db
            chess:
                - name: chess-default
                  players:
                    - MagnusCarlsen
                    - Hikaru
            google_cloud_platform:
                - name: gcp-default
                  project_id: project-0c3c5223-416f-4242-b0f
                  location: us-central1 # see https://cloud.google.com/compute/docs/regions-zones
                  # Option 2: Specify a path to the service account file
                  service_account_file: "/mnt/c/Users/Daniel/DE_zoomcap_2026/05_data_platforms/credentials/gcs_credentials.json"
